### ISSUE TITLE
Create a shareable github action

### ISSUE THREAD

**Issue by elguitar** [Seravo/gnitpick#27]
An user should be able to run gnitpick on their own repo via github actions. This should be as easy as possible and the default parameters should be generic and not too strict.

We should first try this out with Seravo's own projects and later maybe even publish the action.

**Comment by frimro** [comment]
Should we use [workflow templates](https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization#creating-a-workflow-template) for Seravo projects?

**Comment by ypcs** [comment]
> Should we use workflow templates for Seravo projects?

Yes, preferably.

**Comment by frimro** [comment]
Workflow templates were dropped for now, as they required the `.github` repository to be public (or have organization enterprise plan). Using copy-pasted actions between repositories for now.
